# Generated by Django 4.2 on 2023-07-14 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='обо мне'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_notifications',
            field=models.BooleanField(default=False, verbose_name='получать уведомления в телеграм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=32, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='текстовый идентификатор страницы'),
        ),
    ]
