# Generated by Django 4.2 on 2023-09-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_about_me_user_telegram_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=260, unique=True, verbose_name='электронная почта'),
        ),
    ]
