# Generated by Django 4.2 on 2023-09-16 14:15

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=authentication.models._get_default_profile_image, upload_to=authentication.models._get_profile_image_filepath, verbose_name='изображение'),
        ),
    ]
